#!/bin/sh

PIA_USER=`head -1 /etc/openvpn/pia.auth`
PIA_PASS=`tail -1 /etc/openvpn/pia.auth`
PIA_COUNTRY="Japan"

path_to_scripts="/usr/local/pia/manual-connections"
vpn_interface="tun0"

gateway=$(ifconfig ${vpn_interface} 2>/dev/null | grep 'inet addr' | cut -d: -f2 | cut -d' ' -f1 | sed 's/[^\.]*$/1/')

if [ "${ACTION}" = "ifup" -a "${DEVICE}" = "${vpn_interface}" ]; then
    token_script="PIA_USER=${PIA_USER} PIA_PASS=${PIA_PASS} PIA_COUNTRY=${PIA_COUNTRY} ${path_to_scripts}/get_token.sh"
    logger -t hotplug "PIA VPN interface ${vpn_interface} is up. Trying to get the PIA host and token."
    logger -t hotplug ${token_script}
    host_token=$(eval ${token_script})
    host="$(echo ${host_token} | cut -d' ' -f1)"
    token="$(echo ${host_token} | cut -d' ' -f2)"

    logger -t hotplug "Gateway is ${gateway}. Obtained host ${host} and token"
    logger -t hotplug ${token}

    pf_timeout=10
    pf_script="PF_GATEWAY=${gateway} PF_HOSTNAME=${host} PIA_TOKEN=\"${token}\" ${path_to_scripts}/port_forwarding.sh &"
    logger -t hotplug "Starting the port forwarding script with a ${pf_timeout}s time limit."
    logger -t hotplug ${pf_script} 
    eval ${pf_script}
    sleep ${pf_timeout}
    pia_port=$(head -1 ${path_to_scripts}/pia_forwarded_port)
    if [ "${pia_port}" = "" ]; then
      logger -t hotplug "Failed to request port forwarding from PIA. Try to run the command above manually to see what went wrong. Restart the OpenVPN connection to try again."
      exit 1
    fi
    logger -t hotplug "The forwarded port is ${pia_port}."
fi

if [ "${ACTION}" = "ifdown" -a "${GW}" = "" ]; then
    logger -t hotplug "PIA VPN interface was shut down. Will try to kill the port forwarding script in case it's running."
    ps | grep port_forwarding | sed 's/^ //' |  cut -d' ' -f 1 | xargs kill
    rm ${path_to_scripts}/pia_forwarded_port
fi
